package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1



/**
 * Notificacion generated by hbm2java
 */
public class Notificacion implements java.io.Serializable {


     private Integer id;
     private Subasta subasta;
     private String reason;

    public Notificacion() {
    }

    public Notificacion(Subasta subasta, String reason) {
       this.subasta = subasta;
       this.reason = reason;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Subasta getSubasta() {
        return this.subasta;
    }
    
    public void setSubasta(Subasta subasta) {
        this.subasta = subasta;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


