package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rareza generated by hbm2java
 */
public class Rareza implements java.io.Serializable {


     private Integer id;
     private String description;
     private Set cards = new HashSet(0);

    public Rareza() {
    }

	
    public Rareza(String description) {
        this.description = description;
    }
    public Rareza(String description, Set cards) {
       this.description = description;
       this.cards = cards;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getCards() {
        return this.cards;
    }
    
    public void setCards(Set cards) {
        this.cards = cards;
    }




}


