package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reportetipo generated by hbm2java
 */
public class Reportetipo implements java.io.Serializable {


     private Integer id;
     private String description;
     private Set reports = new HashSet(0);

    public Reportetipo() {
    }

	
    public Reportetipo(String description) {
        this.description = description;
    }
    public Reportetipo(String description, Set reports) {
       this.description = description;
       this.reports = reports;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }




}


