package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private BigDecimal moneyAmount;
     private int coinsAmount;
     private Date transactionDate;
     private String transactionType;

    public Transaccion() {
    }

    public Transaccion(Usuario usuario, BigDecimal moneyAmount, int coinsAmount, Date transactionDate, String transactionType) {
       this.usuario = usuario;
       this.moneyAmount = moneyAmount;
       this.coinsAmount = coinsAmount;
       this.transactionDate = transactionDate;
       this.transactionType = transactionType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getMoneyAmount() {
        return this.moneyAmount;
    }
    
    public void setMoneyAmount(BigDecimal moneyAmount) {
        this.moneyAmount = moneyAmount;
    }
    public int getCoinsAmount() {
        return this.coinsAmount;
    }
    
    public void setCoinsAmount(int coinsAmount) {
        this.coinsAmount = coinsAmount;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }




}


